---
# defaults file for ansible
#Global:
#  deploy: embed
#  net:  
#    - working_dir: /home/net
#  embed:
#    - working_dir: /home/embed
Global:
  Working_dir: "{{ lookup('env','HOME') }}/autoinstall-test"
  Ubuntu_ISO: jammy-live-server-amd64.iso
  Ubuntu_ISO_URL: https://cdimage.ubuntu.com/ubuntu-server/jammy/daily-live/current/

Nocloud_net:
    Deploy: true
    http_ip: 172.20.22.118
    http_port: 3003

Static_boot_ip:
    Deploy: true
    ip: 172.20.22.111
    subnet: 255.255.255.0
    gateway: 172.20.22.1

Disk_info:
  Deploy: true
  partition_customization:
    pv0_size: -1
  lv_customization:
      - name: rootlv
        path: /
        size: 10G 

Host_info:
  - Deploy: true
    OS:
      host_name: msh-ubuntu-server1      # Target Ubuntu hostname.
      Locale: en_US                            # Target Ubuntu OS locale
      Keyboardlayout: us                       # Terget Ubuntu OS keyboard layout
      Keyboardvariant: intl 
    Network:
      ip: 10.10.69.243/24
      gateway: 10.10.69.1
      DNS: 8.8.8.8
    Users:
      - username: msh
        Deploy: true
        password: $6$i70a4vD5ZQdhaJrR$8DBnKtf8kxPTBeWaXQvWSym93cQpJYDLJh8oAn4z08dZ3RzpmG9hzP2pCVzWAjYheDw/sOuCAQ9jKOO0lU/T.1
      - username: ansible
        Deploy: true
        password: $6$9yMZWY.i.urnYIV2$jekh9N5WBpFe94tCU1cXIsiAgQuldGK0vKiygqpZs7SBF6LAbm3RFYgu3JUSNfKgEYwpEcYbRbi/O9KJACVbT.
  - Deploy: false                                                    # if True the ISO is going to create.
    OS:
      host_name: msh-ubuntu-server2  
      Locale: en_US                            
      Keyboardlayout: us                      
      Keyboardvariant: intl 
    Network:
      ip: 172.20.22.110/24
      gateway: 172.20.22.1
      DNS: 8.8.8.8
    Users:
      - username: msh
        Deploy: true
        password: "$6$i70a4vD5ZQdhaJrR$8DBnKtf8kxPTBeWaXQvWSym93cQpJYDLJh8oAn4z08dZ3RzpmG9hzP2pCVzWAjYheDw/sOuCAQ9jKOO0lU/T.1"
      - username: ansible
        Deploy: true
        password: "$6$9yMZWY.i.urnYIV2$jekh9N5WBpFe94tCU1cXIsiAgQuldGK0vKiygqpZs7SBF6LAbm3RFYgu3JUSNfKgEYwpEcYbRbi/O9KJACVbT."
