---
# defaults file for ansible
Global_CFG:
  Working_Dir: "{{ lookup('env','HOME') }}/ubuntu-autoinstall"
  Ubuntu_ISO: jammy-live-server-amd64.iso
  #Ubuntu_ISO: ubuntu-22.04.3-live-server-amd64.iso
  Ubuntu_ISO_URL: https://cdimage.ubuntu.com/ubuntu-server/jammy/daily-live/current/
  #Ubuntu_ISO_URL: https://releases.ubuntu.com/jammy/

Nocloud_Net:
    Deploy: false
    Http_Ip: 172.20.22.118
    Http_Port: 3003

Static_Boot_Ip:
    Deploy: false
    Ip: 172.20.22.109
    Subnet: 255.255.255.0
    Gateway: 172.20.22.220

Disk_CFG:
  Deploy: true
  Partition_Customization:
    PV0_Size: -1
  LV_Customization:
      - Name: rootlv
        Path: /
        Size: 10G 
      - Name: homelv
        Path: /home
        Size: 5G
      - Name: varlv
        Path: /var
        Size: 5G
      - Name: varloglv
        Path: /var/log
        Size: 3G
Apt_CFG:
  Deploy: true
  Url: https://ir.ubuntu.sindad.cloud/ubuntu/

Users_CFG:
    Deploy: true
    Users:
      - Deploy: true
        Username: msh
        Sudo: false
        Password: "$6$i70a4vD5ZQdhaJrR$8DBnKtf8kxPTBeWaXQvWSym93cQpJYDLJh8oAn4z08dZ3RzpmG9hzP2pCVzWAjYheDw/sOuCAQ9jKOO0lU/T.1"
      - Deploy: true
        Username: ansible
        Sudo: true
        Password: "$6$9yMZWY.i.urnYIV2$jekh9N5WBpFe94tCU1cXIsiAgQuldGK0vKiygqpZs7SBF6LAbm3RFYgu3JUSNfKgEYwpEcYbRbi/O9KJACVbT."

Package_CFG:
  Deploy: true
  Package_List:
    - traceroute
    - htop
    
Host_CFG:
  - Deploy: true
    OS:
      Host_Name: ibm-blade-server-209     # Target Ubuntu hostname.
      Locale: en_US                            # Target Ubuntu OS locale
      Keyboardlayout: us                       # Terget Ubuntu OS keyboard layout
      Keyboardvariant: intl 
    Network:
      Ip: 172.20.22.109/24
      Gateway: 172.20.22.220
      DNS: 8.8.8.8
  - Deploy: false                                                    # if True the ISO is going to create.
    OS:
      Host_Name: msh-ubuntu-server2  
      Locale: en_US                            
      Keyboardlayout: us                      
      Keyboardvariant: intl 
    Network:
      Ip: 172.20.22.110/24
      Gateway: 172.20.22.1
      DNS: 
        - 8.8.8.8
