---
# tasks file for ansible
#- name: test
#  debug:
#    var: item.working_dir
#  loop: "{{ Global }}"
- name: template-net
  template:
    src: test.j2
    dest: "/root/msh/ubuntu-autoinstall/test-ansible.yaml"
    mode: "666"
  loop: "{{ Global.net }}"
  when: Global.deploy == 'net'
- name: template-embed
  template:
    src: test.j2
    dest: "/root/msh/ubuntu-autoinstall/test-ansible.yaml"
    mode: "666"
  loop: "{{ Global.embed }}"
  when: Global.deploy == 'embed'
